# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:

env_files:
  github_token: /root/projects/keys/main

builds:
  -
    binary: pfwd
    id: pfwd
    ldflags: -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - ppc64
    goarm:
      - 7

release:
  draft: false

archives:
  -
    id: "pfwd"
    builds: ['pfwd']
    format: tar.gz
    name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
    files:
      - COPYING

nfpms:
  -
    id: "pfwd"
    builds: ['pfwd']
    formats:
      - deb
      - rpm
    vendor: "Eltaline <eltaline.ou@gmail.com>"
    homepage: "https://elta.ee/"
    maintainer: "Andrey Kuvshinov <syslinux@protonmail.com>"
    description: "pfwd. Listen inotify events system service"
    license: "GPLv3"
    file_name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"

    bindir: /usr/sbin

    dependencies:
      - systemd
      - logrotate

    contents:

      - dst: "/etc/pfwd"
        type: dir

      - dst: "/var/log/pfwd"
        type: dir

      - src: "conf/systemd/pfwd.service"
        dst: "/lib/systemd/system/pfwd.service"

      - src: "conf/systemd/pfwd.timer"
        dst: "/lib/systemd/system/pfwd.timer"

      - src: "conf/logrotate.d/pfwd"
        dst: "/etc/logrotate.d/pfwd"

    scripts:
      postinstall: "scripts/postinstall.sh"

scoop:

  commit_author:
    name: "Andrey Kuvshinov"
    email: "syslinux@protonmail.com"
  homepage: "https://elta.ee"
  license: "GPLv3"

brews:
 -
   commit_author:
     name: "Andrey Kuvshinov"
     email: "syslinux@protonmail.com"
   homepage: "https://elta.ee/"
   goarm: 7

snapshot:
  name_template: "{{.Version}}-master"
changelog:
  sort: asc
  filters:
    exclude:
    - README
    - OPTIONS
